XIncludeFile "widgets.pbi"

;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;

UseModule Widget

Global Window_0, Canvas_0, winBackColor = $FFFFFF
Global NewMap Widgets.i()

Procedure ReDraw(Canvas)
  If IsGadget(Canvas) And StartDrawing(CanvasOutput(Canvas))
    DrawingMode(#PB_2DDrawing_Default)
    Box(0,0,OutputWidth(),OutputHeight(), winBackColor)
    
    With Widgets()
      ForEach Widgets()
        ;If Canvas = \Canvas\Gadget
        Draw(Widgets())
        ;EndIf
      Next
    EndWith
    
    StopDrawing()
  EndIf
EndProcedure

Procedure Canvas_0_CallBack()
  Protected Repaint, *This.Widget_S
  Protected Canvas = EventGadget()
  Protected Width = GadgetWidth(Canvas)
  Protected Height = GadgetHeight(Canvas)
  Protected MouseX = GetGadgetAttribute(Canvas, #PB_Canvas_MouseX)
  Protected MouseY = GetGadgetAttribute(Canvas, #PB_Canvas_MouseY)
  Protected WheelDelta = GetGadgetAttribute(EventGadget(), #PB_Canvas_WheelDelta)
  
  Select EventType()
      ;Case #PB_EventType_Repaint : Repaint = EventData()
    Case #PB_EventType_Resize : Repaint = 1
      Resize(Widgets("Splitter_1"), #PB_Ignore, #PB_Ignore, Width-2, Height-2)
    Default
      
      If EventType() = #PB_EventType_LeftButtonDown
        SetActiveGadget(EventGadget())
      EndIf
      
      With Widgets()
        ForEach Widgets()
          
          Repaint | CallBack(Widgets(), EventType(), MouseX, MouseY)
          
        Next
      EndWith
      
  EndSelect
  
  If Repaint 
    ReDraw(Canvas)
  EndIf
  
EndProcedure

Procedure Window_0_Resize()
  ResizeGadget(Canvas_0, #PB_Ignore, #PB_Ignore, WindowWidth(Window_0)-20, WindowHeight(Window_0)-50)
EndProcedure

Procedure Window_0_Open(x = 0, y = 0, width = 800, height = 600)
  Window_0 = OpenWindow(#PB_Any, x, y, width, height, "", #PB_Window_SystemMenu|#PB_Window_SizeGadget)
  BindEvent(#PB_Event_SizeWindow, @Window_0_Resize(), Window_0)
  
  ; Demo draw widgets on the canvas
  Canvas_0 = CanvasGadget(#PB_Any,  10, 40, 780, 550, #PB_Canvas_Keyboard)
  BindGadgetEvent(Canvas_0, @Canvas_0_CallBack())
  
  Widgets("Panel_0") = Panel(0, 0, 0, 0) 
  AddItem(Widgets("Panel_0"), -1, "Code")
  Widgets("Editor_0") = Text(0, 0, 180, 230, "Тут будут строки кода", #PB_Widget_AutoSize)
  AddItem(Widgets("Panel_0"), -1, "Form")
  Widgets("Form_0") = Container(20, 20, 210, 210) 
  CloseList()
  CloseList()
  
  Widgets("Tree_0") = Text(0, 0, 80, 30, "Тут будет дерево элементов")
  
  Widgets("Panel_1") = Panel(0, 0, 0, 0) 
  AddItem(Widgets("Panel_1"), -1, "Widgets")
  Widgets("Tree_1") = Text(0, 0, 180, 30, "Тут будет список элементов", #PB_Widget_AutoSize)
  AddItem(Widgets("Panel_1"), -1, "Properties")
  Widgets("Tree_3") = Text(0, 30, 180, 30, "Тут будет свойства элементов", #PB_Widget_AutoSize)
  AddItem(Widgets("Panel_1"), -1, "Events")
  Widgets("Tree_4") = Text(0, 60, 180, 30, "Тут будет событие элементов", #PB_Widget_AutoSize)
  CloseList()
  
  Widgets("Splitter_0") = Splitter(1,1,778, 548, Widgets("Tree_0"), Widgets("Panel_1"))
  Widgets("Splitter_1") = Splitter(1,1,778, 548, Widgets("Panel_0"), Widgets("Splitter_0"), #PB_Splitter_Vertical)
  
  SetState(Widgets("Splitter_1"), 550)
  SetState(Widgets("Splitter_0"), 150)
  
   ;    ;Editor::SetText(Widgets("Panel_0"), "")
  ;   Tree::AddItem(Widgets("Tree_0"), -1, "Window_0")
  ;   
  ;   Tree::AddItem(Widgets("Tree_1"), -1, "Button")
  ;   Tree::AddItem(Widgets("Tree_1"), -1, "String")
  ;   Tree::AddItem(Widgets("Tree_1"), -1, "Text")
  
  ReDraw(Canvas_0)
EndProcedure

Procedure Window_0_Events(event)
  Select event
    Case #PB_Event_CloseWindow
      ProcedureReturn #False
      
    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect
      
    Case #PB_Event_Gadget
      Select EventGadget()
      EndSelect
  EndSelect
  
  ProcedureReturn #True
EndProcedure

Window_0_Open()

Repeat
  Select WaitWindowEvent()
    Case #PB_Event_CloseWindow
      Break
    Case #PB_Event_Gadget
      
  EndSelect
ForEver
; IDE Options = PureBasic 5.70 LTS (MacOS X - x64)
; Folding = +--
; EnableXP