CompilerIf #PB_Compiler_OS = #PB_OS_MacOS 
  IncludePath "/Users/as/Documents/GitHub/Widget/"
CompilerElseIf #PB_Compiler_OS = #PB_OS_Windows
  ;  IncludePath "/Users/as/Documents/GitHub/Widget/"
CompilerElseIf #PB_Compiler_OS = #PB_OS_Linux
  ;  IncludePath "/Users/a/Documents/GitHub/Widget/"
CompilerEndIf

XIncludeFile "module_macros.pbi"
XIncludeFile "module_constants.pbi"
XIncludeFile "module_structures.pbi"
XIncludeFile "module_scroll.pbi"
XIncludeFile "module_text.pbi"
XIncludeFile "module_button.pbi"
XIncludeFile "module_string.pbi"
XIncludeFile "module_editor.pbi"
XIncludeFile "module_tree.pbi"
XIncludeFile "module_listicon.pbi"

;
; This code is automatically generated by the FormDesigner.
; Manual modification is possible to adjust existing commands, but anything else will be dropped when the code is compiled.
; Event procedures needs to be put in another source file.
;

Global Window_0

Global Editor_0, Tree_0, Tree_1

Global *Editor_0, *Tree_0, *Tree_1

Procedure OpenWindow_0(x = 0, y = 0, width = 800, height = 600)
  Window_0 = OpenWindow(#PB_Any, x, y, width, height, "", #PB_Window_SystemMenu)
  Editor_0 = Editor::Gadget(#PB_Any, 10, 40, 550, 550) : *Editor_0 = GetGadgetData(Editor_0)
  Tree_0 = Tree::Gadget(#PB_Any, 570, 40, 220, 180, #PB_Flag_FullSelection) : *Tree_0 = GetGadgetData(Tree_0)
  Tree_1 = Tree::Gadget(#PB_Any, 570, 230, 220, 360, #PB_Flag_FullSelection) : *Tree_1 = GetGadgetData(Tree_1)
  
  Editor::SetText(*Editor_0, "Code")
  Tree::AddItem(*Tree_0, -1, "Window_0")
  
  Tree::AddItem(*Tree_1, -1, "Button")
  Tree::AddItem(*Tree_1, -1, "String")
EndProcedure

Procedure Window_0_Events(event)
  Select event
    Case #PB_Event_CloseWindow
      ProcedureReturn #False

    Case #PB_Event_Menu
      Select EventMenu()
      EndSelect

    Case #PB_Event_Gadget
      Select EventGadget()
      EndSelect
  EndSelect
  
  ProcedureReturn #True
EndProcedure

OpenWindow_0()

Repeat
  Select WaitWindowEvent()
    Case #PB_Event_CloseWindow
      Break
    Case #PB_Event_Gadget
      
  EndSelect
ForEver
; IDE Options = PureBasic 5.62 (MacOS X - x64)
; Folding = --
; EnableXP