* Introduction:

TailBite is a tool that splits the PureBasic.asm file generated by PureBasic 3.92 for Windows from a .pb source file into several asm files, and compiles them into a PureBasic library using different tools included with PureBasic.

Although this can be made manually, this tool allows to compile the final user library in just one step, from the original .pb source file, and requires no ASM knowledge from the user.

The PureLibraries compiled with TailBite use the same format as any other UserLibrary (in fact, they just like any other ASM library). It doesn't mean the functions included in them will be faster than using PureBasic procedures; they will be as fast (or as slow) as the original .pb code.

So, what's the use of a tool like that? In my opinion, it could be useful for any of these purposes:

- Build the base ASM code of a complex library which has first been tested using PureBasic for easy debugging.
- Compile a set of procedures of frequent use, so afterwards only the ones that we use in our code will be included in the executable.
- Release speed-and-size-unoptimized PureLibraries when speed and size don´t matter, or when the author doesn´t know ASM nor C.

What TailBite is finally used for, is not my business. Personally, I want to use it for the first of these reasons. But, if your only motivation is only the third, my advice would be to consider using plain PureBasic procedures, as you won´t get any real advantage by using TailBite and it´ll be easier for you to get help from other PureBasic coders. But it´s up to you.

In the first case, once you get a working stable library, you should dig into the ASM code splitted by TailBite and do some easy optimizations -providing you have some knowledge of ASM-. Not that PureBasic generates unoptimized code -on the contrary-, but coding directly in ASM allows you to go further into optimization, and use some tricks to get a better result, which will make the difference between using a procedure or using an ASM PureLibrary.

In case that you release a library coded with TailBite, I encourage you to release the source code as well, since other people will be able to help you trace bugs or learn from your code. Once again, it´s up to you.


*Terms & Conditions:

TailBite is free, the source code is included an you can do whatever you want with both of them. It is provided AS IS, with no warranty, meaning that the author is not liable for any damage caused by its use or by the libraries compiled through it, nor by damage caused by other programs based on its source code.

Nevertheless, I wouldn´t like nobody to lose any files (it happened once and I still don´t know why or how), so my advice can´t be other than: don´t install nor use TailBite at all. You´ve been warned.

TailBite is not a compiler, it mainly splits an asm file into several asm files. It uses the following external programs for automation of the library building process: PBCompiler.exe, FAsm.exe, polib.exe or lcclib.exe or and Library Maker.exe. These programs are not included in TailBite, and it´s your responsibility to comply with the terms of the licenses of those programs. Just the same as when you use those tools to manually code an ASM PureLibrary.


*Requirements

You need to have the full version of PureBasic 3.90 or 3.91 for Windows installed on your computer. It should work on any Windows version PureBasic works on, but I haven´t been able to test it in all versions yet. If you´re having problems using TailBite in your computer, please contact the author, preferably by e-mail (in Spanish, English or French): mcalderon@inicia.es, or at the international PureBasic forums: http://myforums.purebasic.com.


*Installation

Run TailBite_Installer.exe. You´ll see two text fields, one for the PureBasic folder, another for the TailBite installation folder.

The installer gets the PureBasic folder from the Windows registry, so if that information has been changed, deleted or is wrong, you can select the proper PureBasic folder using the "Browse" button in the right.

TailBite can be installed in any folder. If there´s already an entry in the PureBasic tools preferences named "TailBite", the command directory to that entry will be used. Otherwise, a subdirectory of the PureBasic folder named <code>TailBite</code> is choosen and created by default. You can change it by using the "Browse" button in the right.

If you already had TailBite installed, and you choose the same installation folder, the previous version of TailBite will be overwritten, but any files that don´t belong to the TailBite installation will be preserved (library source files, etc.)

The installer unpacks the necessary files, including: TailBite.exe and TBManager.exe, samples (in the TailBite/Samples/ folder), help file (in PureBasic/Help/) and helper resident files (in PureBasic/Residents/).

The source included in the 'src.pack' file. Put it in the TailBite folder. Then, run TBManager.exe and click on the 'Extract TailBite sources' button. You'll be prompted for an unpack folder, select it and all the TailBite sources will be exctracted there.

The source includes all the PureBasic sources of TailBite, and included files, ASM sources of the helper libraries and html sources of this chm file. To build the TailBite_Installer, just run the TailBite Installer Build.pb file (no need to create an executable, just press F5) and follow instructions.



*Reference Manual

-Using TailBite from PureBasic.
-Using TailBite Manager.
-PureBasic syntax used.
-Debug functions.
-CPU modifiers.
-Modifying the ASM sources.
-Creating Image and Sound plug-ins.
-Creating Gadgets.


*Updating

TailBite includes an updater, available from TailBite Manager, to allow updating to bug fix and beta versions through Internet. When the updater is launched, TailBite Manager is closed and the updater tries to connect to the server where the update files are located. If it succeeds, the update files are downloaded and installed, and TailBite Manager is launched again.

You can also download the full installer from one of these links:

http://www.pureproject.net - Down?
http://www.purearea.net

Beta versions:

http://inicia.es/de/elchoni/TailBite/
http://perso.wanadoo.es/tailbite/

If the updater or the links don´t work for you, just drop me an e-mail and I´ll send you the installer.


*Contact the author

You can contact the author by e-mail or at the PureBasic International Forums:

Author:
Miguel Calderón aka El_Choni
mcalderon@inicia.es

PureBasic International Forums:
http://myforums.purebasic.com


*Aknowledgements:

Thanks to:

Fred: for PureBasic (http://www.purebasic.com) and all the help he gave with TailBite, for his GetProcessList and GetPureBasicFolder procedures, and others I don´t remember

Paul: for testing in Windows 2000 and staying cool when an Alpha version of TailBite deleted his PureBasic installation, for his great PureProject site: http://www.pureproject.net.

Andre: for testing and for his superb PureBasic site: http://www.purearea.net.

Rings: for his ExecuteProgram procedure, and for testing.

Denis: for testing and help.

GPI: for his help and tips in using the title bar button, including tooltip.

Manolo: for not pressing me while I was coding TailBite.

Polo, Justin, freedimension, scurrier, Manner, remi_meier, gnozal, RValois, Dare2, ricardo, Preacher, Andreas, NoahPhense, Shannara, Heis Spiter, Flype, Guimauve, Chris, gansta93, comtois, Geischt, dracflamloc and others: for testing TailBite, for finding lots of bugs and encourage me to finish this tool.

And to others I don't remember right now, for testing, debugging, comments, etc. Thanks.


*History:

-February 9th 2006: Version 1.3 PR 0.1
 +Updated for PB 4.0.
 +Fixed: Tools.prefs handling.

-November 23rd 2005: Version 1.3 Beta 0.2
 +Fixed: incorrect handling of functions with a number as a suffix.
 +Fixed: the help line wasn't being correctly generated when the main function didn't have arguments, and there were variable arguments.

-November 5th 2005: Version 1.3 Beta 0.1
 +Added the /CHM command line option for TailBite, to define the name of the help file, without the ".chm" extension, this way: /CHM:MyHelpFileName.

-May 27th 2005: Version 1.2 PR 1.2
 +Fixed a mistake in the help, in the "Using TailBite from PureBasic" section: "_Init" and "_End" must be suffixes, not prefixes.

-May 26th 2005: Version 1.2 PR 1.1
 +Fixed: strings were not correctly returned yet, when calling other library functions from the same library. I hope this fix is for real now XD

-May 11th 2005: Version 1.2 PR 1.0
 +Fixed: strings were not correctly returned, reported by many (Ufff!).

-April 28th 2005: Version 1.2 Beta 2.6
 +Fixed: problem with structured strings, reported by dige.

-April 11th 2005: Version 1.2 Beta 2.5
 +Fixed: external batch file processing, problem reported by Rings.

-March 2nd 2005: Version 1.2 Beta 2.4
 +IMPORTANT: due to significant changes in the internals of the PureBasic compiler, PureLibraries made with PureBasic versions prior to 3.93, must be recompiled to work with PureBasic 3.93.
 +Fixed: TBManager wasn't saving the last file (reported by sverson).

-March 1st 2005: Version 1.2 Beta 2.3
 +Fixed: 'Pick Current' from TBManager wasn't working.
 +Fixed: 'Check for errors' from TBManager always reported a syntax error (reported by Flype, thanks).

-February 28th 2005: Version 1.2 Beta 2.2
 +Fixed: Help line for vararg functions.

-February 23rd 2005: Version 1.2 Beta 2.1
 +Fixed: TBManager buttons.
 +Now more extensions than *.pb and *.desc can be browsed from TBManager.

-January 17th 2005: Version 1.2 Beta 2.0
 +Fixed: source files were not being kept, even when the option was checked. The temporary folder was not being deleted after making the library.

-January 13th 2005: Version 1.2 Beta 1.11
 +Fixed: Resident files would not be created if a previous resident file with a conflicting definition existed.
 +You can now use "PB_" to prefix your library name.

-January 11th 2005: Version 1.2 Beta 1.10
 +Fixed problem when including PureLibraries with "TB_Include*". Should be fixed this time, thanks to freedimension.

-January 10th 2005: Version 1.2 Beta 1.9
 +Fixed problem when using "_S" as part of a string. Was being treated as a variable name. Thanks to dracflamloc for reporting it.

-November 4th 2004: Version 1.2 Beta 1.8
 +Fixed problem when using PureBasic libraries internal variables.

-November 4th 2004: Version 1.2 Beta 1.7
 +Fixed problem with data section, made TailBite crash in some circumstances.

-November 4th 2004: Version 1.2 Beta 1.6
+Fixed problems with arrays.

-October 26th 2004: Version 1.2 Beta 1.5
 +Fixed "Public align 4" bug.

-October 18th 2004: Version 1.2 Beta 1.4
+Fixed compatibility with PureBasic 3.92 Beta issue.

-July 28th 2004: Version 1.2 Beta 1.3
 +Added TB_Include2DDrawing and TB_IncludeFont helper libraries, to allow including a PureLibrary even if its commands are not used in the library. Not documented in the help file yet.

-July 20th 2004: Version 1.2 Beta 1.2
 +Fixed potential bug when processing pb files marked as 'Shared DLL'.
 +Fixed bug when using the TB_DebugError function, reported by remi_meier.

-July 19th 2004: Version 1.2 Beta 1.1
 +Fixed weird bug when creating the obj text file to feed polib/lcclib.

-July 12th 2004: Version 1.2 Beta 1.0
 +TailBite failed if the "Generate build batch file" option was enabled. Thanks to Paul for his help on finding this one.
 +TBManager remained disabled after TailBite was done.
 +Version number changed to 1.0, because this is a huge fix that was driving me mad ;)

-July 12th 2004: Version 1.2 Beta 0.1
 +Fixed wrong build number, thanks to NoahPhense for reporting this one (now, seriously, this was confusing the updater. Probably;).

-July 11th 2004: Version 1.2 Alpha 0.10
 +Fixed bug when creating the obj files list for polib/lcclib, thanks to comtois for reporting.
 +Now TailBite restarts the compiler automatically.

-July 7th 2004: Version 1.2 Alpha 0.9
 +Fixed problem with helper functions, thanks to freedimension for reporting.

-July 6th 2004: Version 1.2 Alpha 0.8
 +TailBite will use polib.exe if present in the Compilers folder, otherwise it will search for lcclib.exe in the Compilers folder and in the Library SDK folder. If none is found, it'll fail with a message.

-July 6th 2004: Version 1.2 Alpha 0.7
 +Fixed bug in the TB_Debugger helper function, thanks to freedimension for reporting.</li>

-June 24th 2004: Version 1.2 Alpha 0.6
 +Fixed bug in TBManager: wrong number of arguments in a timer procedure made TBManager crash in NT 4 and misbehave in other Windows versions. Thanks to Rings for reporting.

-June 6th 2004: Version 1.2 Alpha 0.5

 +Fixed problem with Windows 2000 and Windows XP: TBManager's controls remained grayed when TailBite had finished (Mutex name issue in CheckTBDone() timer procedure). Reported by Paul, thx, Paul ;)

-June 6th 2004: Version 1.2 Alpha 0.5

 +Fixed problem with Windows 2000 and Windows XP: TBManager's controls remained grayed when TailBite had finished (Mutex name issue in CheckTBDone() timer procedure). Reported by Paul, thx, Paul ;)


-June 2nd 2004: Version 1.2 Alpha 0.4

 +Fixed problem with some duplicate obj files.


-May 31st 2004: Version 1.2 Alpha 0.3

 +Fixed problem with helper functions.


-May 28th 2004: Version 1.2 Alpha 0.2

 +Fixed problem with multidimensional arrays.

-May 25th 2004: Version 1.2 Alpha 0.1
 +Changed version number XD.
 +Helper libraries are no longer installed, but included when needed.

-May 24th 2004: Version 1.1 PR 1.2
 +TailBite helper libraries will be included in the libraries using them, so they don't have to be included with the library.
 +TailBite will compile any hhp file it finds, if HTML Help Workshop is installed, or copy the html help files to the help directory folder.
 +Fixed: desc file processing when comments were found.

-April 28th 2004: Version 1.1 PR 1.1
 +Improved the Installer.

-April 26th 2004: Version 1.1 PR 1.0
 +Changed version name, sent to Andre ;)

-April 22th 2004: Version 1.1 Beta 0.6
 +Changed: if the source hasn't been saved, TailBite names the lib "TB_TempLib", to avoid creating a different library each time.
 +Fixed minor bugs.
 +Updated some parts of the help file.

-April 20th 2004: Version 1.1 Beta 0.5
 +Added: Description if _Init and _End functions, forgot about this...
 +Added: TailBite will attempt to create a resident file instead of a library if the source code has no procedures.
 +Added: TailBite will prompt for a help file/directory name if no previous library with the same name exists.
  Otherwise, it will use the previous help file/directory name.
 +Fixed: TailBite didn't ask before deleting a previous library with the same name, even if that option was chosen from TBManager.

-April 19th 2004: Version Version 1.1 Beta 0.4
 +Fixed: TailBite status window didn't close unless 'Cancel' was pressed.
 +Fixed: TailBite didn't ask before deleting a previous library with the same name, even if that option was chosen from TBManager.

-April 18th 2004: Version 1.1 Beta 0.3
 +Fixed some problems in TBManager.

-April 16th 2004: Version 1.1 Beta 0.2
 +Fixed TB_Gadget helper lib. You can create gadgets again.

-April 14th 2004: Version 1.1 Beta 0.1
 +Now works with PB 3.90.
 +Fixed: asm data processing got stuck due to a modifocation of PureBasic.asm in PB 3.90.
 +Fixed: crashing when the original code included a commented procedure.
 +Removed MyMDI sample since PB includes an MDIGadget now and the sample is totally useless ("thank you", Fr3ak XXDD).
 +Added: TailBite restarts the compiler when library is made.
 +Added: Support for Static variables.

-March 18th 2004: Version 1.0 PR 1.1
 +Fixed direct ASM processing due to a bug in PureBasic 3.89 Beta: the ASM file produced when using the /COMMENTED option strips some parts of the code.

-March 8th 2004: Version 1.0 PR 1.0
 +First Release Version.

-March 3rd 2004: Version 1.0 Beta 10.30
 +Enhanced title button in TBManager.
 +Added help multilanguage support.
 +Fixed source file copy when processing .Desc files.
 +Fixed processing of End statements.

-February 26th 2004: Version 1.0 Beta 10.26
 +Fixed processing of recursive ProcedureDLLs.
 +Fixed local labels bug.
 +Improved API function names recognition.
 +Fixed potential problems with comments.
 +Fixed conflict with Danilo's ToolBarPro lib in a test file.

-February 24th 2004: Version Version 1.0 Beta 10.22
 +Fixed TailBite sources extraction.

-February 18th 2004: Version 1.0 Beta 10.19
 +Fixed processing of recursive procedures.
 +Fixed TailBite processing of _PB_EOP_NoValue.
 +Fixed TailBite Manager stay on top caption button activating.

-February 18th 2004: Version 1.0 Beta 10.14
 +Fixed .desc files processing.
 +Fixed making residents.
 +Added MyMDI sample.
 +Fixed inline ASM for jaPBe.
 +Added download links.

-February 10th 2004: Version 1.0 Beta 9.03
 +Added TB_GadgetExtension library and sample.
 +Help updated.

-January 19th 2004: Version 1.0 Beta 6
 +First version which starts tracking changes and history.